spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/geometry
    username: postgres
    password: amiri
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate